### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nicman23** [nicman23/ssh-makepkg#3]
- [ ] Add editing for pkgbuilds
- [ ] Sending edited pkgbuilds
- [ ] Add more support for some wierd package names (not sure what will come up)

**Comment by nicman23** [comment]
implemented hooks and editor

wierd package names supported
